services:
  - type: web
    name: course-booking-app
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: zerokosthealthcare@gmail.com
      - key: SMTP_PASS
        value: mfna ghqt dnvo psso
      - key: FROM_EMAIL
        value: zerokosthealthcare@gmail.com
      - key: FROM_NAME
        value: ZeroKost Healthcare
      - key: OWNER_EMAIL
        value: zerokosthealthcare@gmail.com
